### ======================================
### AUTHORS
### ======================================

POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "Robert C. Martin",
  "nationality": "American"
}

###

POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "Joshua Bloch",
  "nationality": "American"
}

###

POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "Martin Fowler",
  "nationality": "Australian"
}

###

POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "Erich Gamma",
  "nationality": "Swiss"
}

###

POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "Andrew Hunt",
  "nationality": "American"
}

###

GET http://localhost:8080/authors

### ======================================
### USERS
### ======================================

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Alice Johnson",
  "email": "alice@example.com"
}

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Bob Smith",
  "email": "bob@example.com"
}

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Charlie Brown",
  "email": "charlie@example.com"
}

###

GET http://localhost:8080/users

### ======================================
### BOOKS
### ======================================

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Clean Code",
  "authorId": 1
}

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Clean Architecture",
  "authorId": 1
}

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Effective Java",
  "authorId": 2
}

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Refactoring",
  "authorId": 3
}

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Design Patterns",
  "authorId": 4
}

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "authorId": 5
}

###

GET http://localhost:8080/books

###

POST http://localhost:8080/books/2/borrow
Content-Type: application/json

{
  "userId": 1
}

###
PUT http://localhost:8080/books/1/return

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Moetaz",
  "email": "moetaztrojet@example.com",
  "password": "rinmo7620"
}
###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "moetaztrojet@example.com",
  "password": "rinmo7620"
}
###
GET http://localhost:8080/books

###
DELETE http://localhost:8080/books/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2V0YXp0cm9qZXRAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODU5NjY4ODYsImV4cCI6MTc4NTk3MDQ4Nn0.jY_0gsyo6lMO4SmAVx_J6DZk8a8phOH4QoDfLENydxM
