### Get all books
GET http://localhost:8080/books

###

### Get one book
GET http://localhost:8080/books/3

###

### Create a book
POST http://localhost:8080/books
Content-Type: application/json

{
  "id": 4,
  "title": "Harry Potter",
  "author": "J.K. Rowling"
}

###

### Get all books again
GET http://localhost:8080/books

###
DELETE http://localhost:8080/books/2

###
PUT http://localhost:8080/books/3
Content-Type: application/json

{
  "id": 999,
  "title": "Harry Potter",
  "author": "J.K. Rowling"
}
###
GET http://localhost:8080/books
